# configuration for "master" branch
-
  branches:
    only:
      - master
  skip_tags: true
  version: '{build}'
  environment:
    GitHubToken:
      secure: I74wB8tW0coqem3AUmm4Vlo0GZjcm7wq0+yLC9NygN+HDHwBUNWNuhg94hZz3IKl
  build_script:
    - ps: .\Pask.ps1 Release
  artifacts:
    - path: .build\output\*.vsix
  deploy: off
  test: off

# configuration for branches
-
  branches:
    except:
      - master
  skip_tags: true
  version: '{build}'
  build_script:
    - ps: .\Pask.ps1
  artifacts:
    - path: .build\output\*.vsix
  deploy: off
  test: off