# configuration for "master" branch
-
  branches:
    only:
      - master
  skip_tags: true
  version: '{build}'
  build_script:
    - ps: .\Pask.ps1 Release
  artifacts:
    - path: .build\output\*.vsix
  deploy: off
  test: off

# configuration for branches
-
  branches:
    except:
      - master
  skip_tags: true
  version: '{build}'
  build_script:
    - ps: .\Pask.ps1
  artifacts:
    - path: .build\output\*.vsix
  deploy: off
  test: off